apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/weammakhoul/frontend-service:dev-8b96f8b6cc2834a3dbeee2321d37599d79685aba
          ports:
            - containerPort: 3000
