apiVersion: apps/v1
kind: Deployment
metadata:
  name: img-proc-mcp
  labels:
    app: img-proc-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: img-proc-mcp
  template:
    metadata:
      labels:
        app: img-proc-mcp
    spec:
      containers:
        - name: img-proc-mcp
          image: docker.io/weammakhoul/img-proc-mcp-service:k8s-3b6c431a51ff
          ports:
            - containerPort: 8090
          env:
            - name: MCP_TRANSPORT
              value: "streamable-http"
            - name: MCP_HOST
              value: "0.0.0.0"
            - name: MCP_PORT
              value: "8090"
            - name: DEBUG_OBJECT_SELECTION
              value: "0"
