apiVersion: v1
kind: Service
metadata:
  name: img-proc-mcp-svc
  labels:
    app: img-proc-mcp
spec:
  selector:
    app: img-proc-mcp
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
