apiVersion: v1
kind: Service
metadata:
  name: yolo-svc
  labels:
    app: yolo
spec:
  selector:
    app: yolo
  sessionAffinity: ClientIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
