apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-prod-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: prod
    name: grafana-pvc
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-04757c81c1e1a6ec7
    fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - us-east-1b
