ami_id            = "ami-0b6d9d3d33ba97d99"
availability_zone = "us-east-1d"
env               = "dev"
instance_type     = "t2.nano"
key_pair_name     = "makhoul-polyai-dev-key"
region            = "us-east-1"
s3_bucket_prefix  = "makhoul-polyai-dev-"
