apiVersion: apps/v1
kind: Deployment
metadata:
  name: img-proc-mcp
  labels:
    app: img-proc-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: img-proc-mcp
  template:
    metadata:
      labels:
        app: img-proc-mcp
    spec:
      containers:
        - name: img-proc-mcp
          image: docker.io/weammakhoul/img-proc-mcp-service:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8090
          envFrom:
            - configMapRef:
                name: img-proc-mcp-config
