apiVersion: v1
kind: Service
metadata:
  name: yolo-svc
  labels:
    app: yolo
spec:
  type: ClusterIP
  selector:
    app: yolo
  sessionAffinity: ClientIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
