apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo
  labels:
    app: yolo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
        - name: yolo
          image: docker.io/weammakhoul/yolo-service:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: yolo-config
