apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - namespace.yaml

# Build and push these images before applying this overlay.
images:
  - name: docker.io/weammakhoul/yolo-service
    newTag: k8s-dev-078713f552381d5f055d2ce68a572548e5b2ffa1
  - name: docker.io/weammakhoul/agent-service
    newTag: k8s-dev-078713f552381d5f055d2ce68a572548e5b2ffa1
  - name: docker.io/weammakhoul/frontend-service
    newTag: k8s-dev-078713f552381d5f055d2ce68a572548e5b2ffa1
  - name: docker.io/weammakhoul/img-proc-mcp-service
    newTag: k8s-dev-078713f552381d5f055d2ce68a572548e5b2ffa1
