name: Deploy Yolo

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev instance
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEV_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.DEV_INSTANCE_SSH_KEY }}
          script: |
            cd /home/ubuntu/PolyAI
            git fetch origin
            git reset --hard origin/dev

            if [ ! -d "/home/ubuntu/PolyAI/.venv" ]; then
              python3 -m venv /home/ubuntu/PolyAI/.venv
            fi

            /home/ubuntu/PolyAI/.venv/bin/pip install --upgrade pip
            /home/ubuntu/PolyAI/.venv/bin/pip install -r /home/ubuntu/PolyAI/services/yolo/requirements.txt
            /home/ubuntu/PolyAI/.venv/bin/pip install -r /home/ubuntu/PolyAI/services/yolo/torch-requirements.txt


            sudo systemctl daemon-reload
            sudo systemctl restart yolo.service
            sudo systemctl status yolo.service --no-pager

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Prod instance
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.PROD_INSTANCE_SSH_KEY }}
          script: |
            cd /home/ubuntu/PolyAI
            git fetch origin
            git reset --hard origin/main

            if [ ! -d "/home/ubuntu/PolyAI/.venv" ]; then
              python3 -m venv /home/ubuntu/PolyAI/.venv
            fi

            /home/ubuntu/PolyAI/.venv/bin/pip install --upgrade pip
            /home/ubuntu/PolyAI/.venv/bin/pip install -r /home/ubuntu/PolyAI/services/yolo/requirements.txt
            /home/ubuntu/PolyAI/.venv/bin/pip install -r /home/ubuntu/PolyAI/services/yolo/torch-requirements.txt

            sudo systemctl daemon-reload
            sudo systemctl restart yolo.service
            sudo systemctl status yolo.service --no-pager